# Fonts
font_family      JetBrains Mono Nerd Font 
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12.0

# Cursor
cursor_shape underline 
#cursor_beam_thickness 1.5 
cursor_underline_thickness 2.0

# Background 
background_opacity 0.9
# foreground #a9b1d6
# background #24283b

# Hide Mouse
mouse_hide_wait 3.0

# Hyperlink
underline_hyperlinks always 
detect_urls yes
open_url_with default
# url_color #df7234
url_style curly

# Misc
scrollback_lines 500

# Window
window_margin_width 15
window_padding_width 5
hide_window_decorations titlebar-only

tab_bar_edge top
tab_bar_margin_width 15.0
tab_bar_margin_height 30.0 3.0

tab_bar_style powerline

macos_show_window_title_in none

# Key bindings
map ctrl+c
map ctrl+v
copy_on_select yes


# BEGIN_KITTY_THEME
# Earthsong
include current-theme.conf
# END_KITTY_THEME
